version: "3.9"
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/shorten-url
    ports:
      - "3000:3000"
    # environment:
      # - MYSQL_ROOT_PASSWORD=1qazxW2!
      # - MYSQL_USER=root
      # - MYSQL_PORT=3309
      # - MYSQL_USER_PASSWORD=1qazxW2!
      # - MYSQL_DATABASE_HOST=kubernetes.docker.internal
      # - REDIS_URL=redis://redis:6379/

